name: PASTA Gatekeeper Build

on:
  push:
    branches: [ main, staging, development ]
  pull_request:
    branches: [ main, staging, development ]
  workflow_dispatch:
    branches: [ main, staging, development ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment-min.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check website status
      run: |
        cd webapp
        cp config.py.template config.py
        sed -i "s/<PATH TO PROJECT ROOT>/${PWD//\//\\/}/" config.py
        python main.py&
        sleep 5
        if curl -sSf http://127.0.0.1:8088/ > /dev/null; then
          echo "Website is up and running"
        else
          echo "Website is down"
          exit 1
        fi
